### ISSUE TITLE
[v20.1.0] Config listing request not working

### ISSUE THREAD

**Issue by Granyy** [gocd/api.go.cd#635] opened 2020-03-06 14:06 UTC
Hello,

I recently updated the version of my GoCD server from 19.5.0 to 20.1.0 version.
Everything goes well except that I cannot access to pipeline groups listing (https://api.gocd.org/current/#config-listing).

**REQUEST:**
```
curl --location --request GET 'http://localhost:8153/go/api/config/pipeline_groups' \
--header 'Authorization: bearer <MY_TOKEN>'

```

**RESPONSE:**
```
404 Not Found
{
    "message": "Either the resource you requested was not found, or you are not authorized to perform this action."
}
```

What I am missing?

Thank you for your help,
Best regards,
Granyy

**Comment by GaneshSPatil** [comment] 2020-03-06 15:11
Hi Granyy,

It looks like this issue is duplicate of https://github.com/gocd/gocd/issues/7521

The unversioned pipeline group config listing API was deprecated as part of GoCD release `v19.12.0` and put behind a toggle.

Refer https://github.com/gocd/gocd/issues/7521#issuecomment-569860496 to use the deprecated pipeline group config listing API.

Refer https://github.com/gocd/gocd/issues/7521#issuecomment-570120109 to use the alternative pipeline group API.

I will be closing this issue as duplicate/resolved. If you've any further questions, feel free to reopen the issue.

**Closed by GaneshSPatil** 2020-03-06 15:11 UTC

**Comment by Granyy** [comment] 2020-03-09 08:23
Thank you for your answer. I haven't found the previous issue, sorry about that.
